### PR TITLE
store projection error objects

### LINKED ISSUE #397: A better exception processing for the projections
See how symfony messenger solves the problem

### PR DESCRIPTION
**Pull request by DavidBadura**
fix #397

### CODE REVIEW

File: src/Console/Command/ProjectionStatusCommand.php [hunk 1]
```diff
@@ -4,45 +4,97 @@
...
                 ],
-                [...$projections],
-            ),
+            ],
         );
 
+        $errorObject = $projection->errorObject();
+
+        if ($errorObject) {
+            dump($errorObject);
```
Comment (DanielBadura) [inline src/Console/Command/ProjectionStatusCommand.php]: should be removed

**Review by DanielBadura — CHANGES_REQUESTED** [review]

File: src/Console/Command/ProjectionStatusCommand.php (hunk 1 above)
Comment (DavidBadura) [reply src/Console/Command/ProjectionStatusCommand.php]: I want to dump the exception

Comment (DavidBadura) [reply src/Console/Command/ProjectionStatusCommand.php]: replaced

**Review by DanielBadura — APPROVED** [review]
