### PR TITLE
fix case insensitive column names

### LINKED ISSUE #165: postgres case insensitive column names
Postgres columns always seem to be created in lowercase. Saving the data works without any problems. But when reading you get the column names in lowercase.

Example:

`recordedOn` => `recordedon`

There is then an error when accessing the array. Another field is also affected: `aggregateId`.

The solution would be to create the columns in `lowersnakecase`. But that would be a **BC break** because you would have to adapt the scheme.

Otherwise you would have to fix the data in the store so that the data can be loaded from Postgres.

### PR DESCRIPTION
**Pull request by DavidBadura**
fix #165 

and added integration tests for:

* sqlite
* postgres: 9.4, 13, 14
* mysql: 5.7, 8.0
* mariadb: 10.0, 10.2, 10.5

### CODE REVIEW

File: src/Store/DoctrineStore.php [hunk 1]
```diff
@@ -55,7 +63,10 @@ private static function normalizeRecordedOn(string $recordedOnAsString, Abstract
         return $recordedOn;
     }
 
-    private static function normalizePlayhead(string $playheadAsString, AbstractPlatform $platform): int
+    /**
+     * @param string|int $playheadAsString
```
Comment (DanielBadura) [inline src/Store/DoctrineStore.php:67]: we should adjust the type for `normalizeResult` parameter too then.

**Review by DanielBadura — APPROVED** [review]
